### ISSUE TITLE
AdGuard - Option to configure `ipFamilyPolicy` and `ipFamilies` for services

### ISSUE THREAD

**Issue by hertznsk** [rm3l/helm-charts#86]
Thanks for the AdGuard chart!

By default, Kubernetes services are created to work only on the IPv4 stack.
If, like me, you have a dual stack network, you need to add settings to the services:

```yaml
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
```

Could you provide the appropriate service configuration options in the chart?
